services:
  api:
    container_name: manager_api
    build:
      context: api/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    networks:
      - manager_network
  
  web:
    container_name: manager_web
    build:
      context: web/
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - manager_network
  
  db:
    container_name: manager_db
    image: postgres:16.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - manager_network
    volumes:
      - manager_db_data:/var/lib/postgresql/data

volumes:
  manager_db_data:

networks:
  manager_network:
    driver: bridge